title: The Met Agency
email: "hello@themetagency.com"
description: "Kobot is."
baseurl: ""
url: "http://themetagency.com"
twitter_username: themetagency
github_username: ""
markdown: kramdown
collections:
  - case-studies
  - staff-members
