title: The Met Agency
email: "hello@themetagency.com"
description: "The Met is a different kind of advertising agency—we concentrate on getting to know you and understanding your needs, because we believe great relationships produce great outcomes."
baseurl: ""
url: "http://themetagency.com"
twitter_username: themetagency
github_username: ""
markdown: kramdown
poops: "farts"
