title: Kobot
email: "info@kobot.ca"
description: "Kobot is."
baseurl: ""
url: "http://themetagency.com"
twitter_username: themetagency
github_username: ""
markdown: kramdown
collections:
  - case_studies:
    - output: true
    permalink: /case-studies/:path/
  
